# Generated by Django 6.0.6 on 2026-07-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key_n', models.BigIntegerField()),
                ('public_key_e', models.BigIntegerField()),
                ('private_key_d', models.BigIntegerField()),
                ('original_number', models.BigIntegerField()),
                ('encrypted_number', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
